import {
  ArrowRight,
  Bell,
  CalendarDays,
  CheckCheck,
  Check,
  CircleAlert,
  CircleCheckBig,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  Clock3,
  Columns3,
  Copy,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  Filter,
  FileJson,
  FileText,
  LockKeyhole,
  LogOut,
  FolderCog,
  FolderOpen,
  Globe,
  GripVertical,
  HardDrive,
  Image,
  KeyRound,
  LayoutDashboard,
  type LucideIcon,
  LoaderCircle,
  Mail,
  MoreHorizontal,
  Minus,
  PanelLeft,
  PanelLeftClose,
  Package,
  Pencil,
  Plug,
  Plus,
  Puzzle,
  RefreshCw,
  Save,
  Search,
  Server,
  Settings2,
  Sparkles,
  Shield,
  ShieldCheck,
  Trash2,
  TriangleAlert,
  Upload,
  UserRound,
  Users,
  X,
  XCircle
} from "lucide-react";
import { cn } from "../../../utils/class-names.js";
import type { IconProps } from "./icon.types.js";

const ICONS: Record<string, LucideIcon> = {
  "arrow-right": ArrowRight,
  bell: Bell,
  "calendar-days": CalendarDays,
  check: Check,
  "check-check": CheckCheck,
  "circle-alert": CircleAlert,
  "circle-check-big": CircleCheckBig,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "chevron-right": ChevronRight,
  "clock-3": Clock3,
  "columns-3": Columns3,
  copy: Copy,
  database: Database,
  download: Download,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  filter: Filter,
  "file-json": FileJson,
  "file-text": FileText,
  "folder-cog": FolderCog,
  "folder-open": FolderOpen,
  globe: Globe,
  "grip-vertical": GripVertical,
  "hard-drive": HardDrive,
  image: Image,
  "key-round": KeyRound,
  "layout-dashboard": LayoutDashboard,
  "loader-circle": LoaderCircle,
  "lock-keyhole": LockKeyhole,
  "log-out": LogOut,
  mail: Mail,
  "more-horizontal": MoreHorizontal,
  minus: Minus,
  package: Package,
  "panel-left": PanelLeft,
  "panel-left-close": PanelLeftClose,
  pencil: Pencil,
  plug: Plug,
  plus: Plus,
  puzzle: Puzzle,
  "refresh-cw": RefreshCw,
  save: Save,
  search: Search,
  server: Server,
  "settings-2": Settings2,
  sparkles: Sparkles,
  shield: Shield,
  "shield-check": ShieldCheck,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  upload: Upload,
  "user-round": UserRound,
  users: Users,
  x: X,
  "x-circle": XCircle
};

export type IconName = keyof typeof ICONS;
export const ICON_NAMES = Object.keys(ICONS).sort();

/**
 * Icon keeps the icon registry inside the UI package so admin contributions can
 * stay string-based and not depend on React icon components directly.
 */
export function Icon({ className, name, ...props }: IconProps) {
  const Component = ICONS[name];

  if (!Component) {
    return null;
  }

  return <Component className={cn("h-4 w-4 shrink-0", className)} {...props} />;
}
