import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import test from "node:test";
import mongoose from "mongoose";
import { CoreOperationAuthorizer, USERS_ENTITY, UsersRepository } from "@trinacria-cms/core-pack/runtime";
import { createMongoDbAdapter, createUserOperationContext, EntityRegistry, MongoDurableEventStore, registerPlatformEntities } from "@trinacria-cms/kernel/runtime";
import { CONTENT_TYPES_ENTITY } from "../src/modules/content-types/content-types.schemas.js";
import { ContentTypesRepository } from "../src/modules/content-types/repositories/content-types.repository.js";
import { ContentTypesService } from "../src/modules/content-types/services/content-types.service.js";
import { ENTRIES_ENTITY } from "../src/modules/entries/entries.schemas.js";
import { EntriesRepository } from "../src/modules/entries/repositories/entries.repository.js";
import { EntriesService } from "../src/modules/entries/services/entries.service.js";
import { ENTRY_REVISIONS_ENTITY } from "../src/modules/revisions/revisions.schemas.js";
import { RevisionsRepository } from "../src/modules/revisions/revisions.repository.js";
import { EditorialDeliveryService } from "../src/modules/publications/delivery.service.js";
import { PUBLICATION_POINTERS_ENTITY, PUBLICATION_SNAPSHOTS_ENTITY } from "../src/modules/publications/publications.schemas.js";
import { PublicationsRepository } from "../src/modules/publications/publications.repository.js";
import { EditorialEntryOperations } from "../src/operations/editorial-entry-operations.js";
import { readPreviewConfig } from "../src/modules/preview/preview-config.js";
import { PREVIEW_CREDENTIALS_ENTITY } from "../src/modules/preview/preview.schemas.js";
import { EditorialPreviewService } from "../src/modules/preview/preview.service.js";

test("preview configuration requires separate keys and exact unique site origins", () => {
  assert.equal(readPreviewConfig({}), null);
  assert.throws(() => readPreviewConfig({ CMS_PREVIEW_ACTIVE_KEY_ID: "active" }), /Incomplete/);
  const key = randomBytes(32).toString("base64");
  const env = { NODE_ENV: "production", CMS_PREVIEW_ACTIVE_KEY_ID: "active", CMS_PREVIEW_KEYS_JSON: JSON.stringify({ active: key }), CMS_PREVIEW_SITES_JSON: JSON.stringify([{ id: "site", origin: "https://site.example" }]) };
  assert.ok(readPreviewConfig(env));
  assert.throws(() => readPreviewConfig({ ...env, CMS_JWT_SECRET: key }), /separate/);
  for (const origin of ["http://site.example", "https://site.example/path", "https://user:pass@site.example", "https://site.example/"]) assert.throws(() => readPreviewConfig({ ...env, CMS_PREVIEW_SITES_JSON: JSON.stringify([{ id: "site", origin }]) }));
});

test("preview token exchange is single-use across replicas; sessions are hashed, scoped, expiring and freshly authorized", { skip: process.env.TRINACRIA_RUN_MONGO_INTEGRATION !== "1" }, async () => {
  const connection = await mongoose.createConnection("mongodb://trinacria:trinacria@127.0.0.1:27017/?authSource=admin", { dbName: `trinacria_preview_${randomUUID().replaceAll("-", "")}` }).asPromise();
  const registry = new EntityRegistry(); registerPlatformEntities(registry);
  for (const entity of [USERS_ENTITY, CONTENT_TYPES_ENTITY, ENTRIES_ENTITY, ENTRY_REVISIONS_ENTITY, PUBLICATION_POINTERS_ENTITY, PUBLICATION_SNAPSHOTS_ENTITY, PREVIEW_CREDENTIALS_ENTITY]) registry.register(entity);
  const db = createMongoDbAdapter({ connection, entityRegistry: registry });
  const store = new MongoDurableEventStore(db, registry, { async describe(ownerPluginId, name, payload) { return { ownerPluginId, eventName: `${ownerPluginId}:${name}`, payloadVersion: 1, payload, recipients: [] }; }, async dispatch() { throw new Error("No consumer"); } }, { instanceId: "preview-test" });
  let canRead = true, now = Date.now();
  const users = new UsersRepository(db), typesRepo = new ContentTypesRepository(db), types = new ContentTypesService(typesRepo, db), publications = new PublicationsRepository(db);
  const authorizer = new CoreOperationAuthorizer({ async can(request) { return { allowed: ["create", "update"].includes(request.action) || (canRead && request.action === "read") }; }, async assert() {} });
  const entries = new EntriesService(new EntriesRepository(db), types, new RevisionsRepository(db), undefined, db, undefined, false, store, publications);
  const operations = new EditorialEntryOperations(entries, authorizer), delivery = new EditorialDeliveryService(publications, typesRepo, { async validateUse() { return []; } }, authorizer);
  const config = { activeKeyId: "preview-only", keys: new Map([["preview-only", randomBytes(32)]]), sites: new Map([["site", "https://site.example"], ["other", "https://other.example"]]) };
  const replicas = [0, 1].map(() => new EditorialPreviewService(db, config, { getUserById: (id) => users.findById(id) }, operations, typesRepo, delivery, () => now));
  const preview = replicas[0]!;
  try {
    await store.initialize(); await db.ensureIndexes("editorial-pack", ["preview_credentials", "content_types", "entries", "entry_revisions", "publication_pointers", "publication_snapshots"]);
    const user = await users.create({ email: "preview@example.test", firstName: "Preview", lastName: "Author" });
    const otherUser = await users.create({ email: "other@example.test", firstName: "Other", lastName: "Author" });
    const context = createUserOperationContext(user.id);
    const type = await types.createContentType({ key: "article", name: "Article", fields: [{ key: "internal", label: "Private", type: "text", multiple: false, required: false }], workflowId: "direct", delivery: { enabled: true, publicFields: [], exposeTitle: true, exposeBody: true, exposeSlug: true } }, user.id);
    const entry = await entries.createEntry({ contentTypeId: type.id, slug: "draft", title: "Working draft", data: { internal: "Private notes" } }, user.id);
    const otherEntry = await entries.createEntry({ contentTypeId: type.id, slug: "other", title: "Other entry", data: {} }, otherUser.id);
    assert.equal(await delivery.get("article", "draft"), null);
    await assert.rejects(preview.issue(context, otherEntry.id, "site"));
    const issued = await preview.issue(context, entry.id, "site");
    assert.equal(issued.formAction, "https://site.example/preview");
    assert.ok(!issued.formAction.includes(issued.token));
    await assert.rejects(preview.exchange(issued.token, "other", "https://other.example"));
    await assert.rejects(preview.exchange(issued.token, "site", "https://attacker.example"));
    const races = await Promise.allSettled(replicas.map((service) => service.exchange(issued.token, "site", "https://site.example")));
    assert.equal(races.filter((result) => result.status === "fulfilled").length, 1);
    const accepted = races.find((result) => result.status === "fulfilled") as PromiseFulfilledResult<Awaited<ReturnType<EditorialPreviewService["exchange"]>>>;
    const session = accepted.value;
    const visible = await replicas[1]!.read(session.sessionId, "site", "https://site.example", entry.id);
    assert.equal(visible?.title, "Working draft"); assert.deepEqual(visible?.data, {});
    const rows = await db.repository("preview_credentials", { pluginId: "editorial-pack" }).findMany({});
    assert.equal(rows.length, 2); assert.ok(!JSON.stringify(rows).includes(session.sessionId)); assert.ok(!JSON.stringify(rows).includes(issued.token));
    await assert.rejects(preview.read(session.sessionId, "site", "https://site.example", otherEntry.id));
    canRead = false; await assert.rejects(preview.read(session.sessionId, "site", "https://site.example", entry.id), { code: "operation_forbidden" });
    canRead = true; await users.updateStatus(user.id, { status: "suspended" });
    await assert.rejects(preview.read(session.sessionId, "site", "https://site.example", entry.id));
    await users.updateStatus(user.id, { status: "active" });
    await preview.revoke(session.sessionId, "site", "https://site.example");
    await assert.rejects(replicas[1]!.read(session.sessionId, "site", "https://site.example", entry.id));
    const expired = await preview.issue(context, entry.id, "site"); now += 61000;
    await assert.rejects(preview.exchange(expired.token, "site", "https://site.example"));
    const fresh = await preview.issue(context, entry.id, "site"), session2 = await preview.exchange(fresh.token, "site", "https://site.example");
    now += 600001; await assert.rejects(preview.read(session2.sessionId, "site", "https://site.example", entry.id));
    const disabled = new EditorialPreviewService(db, null, { getUserById: (id) => users.findById(id) }, operations, typesRepo, delivery);
    await assert.rejects(disabled.issue(context, entry.id, "site"), { code: "service_unavailable" });
  } finally { await store.close(); await connection.dropDatabase(); await connection.close(); }
});
